queue_rules:
  - name: shared_queue
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      #- base=main
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: shared_queue
